# Generated by Django 4.2.23 on 2025-07-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('estado_civil', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
            ],
        ),
    ]
