# Generated by Django 4.2.23 on 2025-07-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('sexo_biologico', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('estado_civil', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('possui_convenio_medico', models.BooleanField(default=False)),
                ('convenio_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_carteirinha', models.CharField(blank=True, max_length=50, null=True)),
                ('validade_carteirinha', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_eh_paciente', models.BooleanField(default=True)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('telefone_responsavel', models.CharField(max_length=20)),
                ('email_responsavel', models.EmailField(max_length=254)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('forma_pagamento', models.CharField(choices=[('cartao', 'Cartão'), ('boleto', 'Boleto'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('estado_civil', models.CharField(max_length=50)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato_emergencia', to='pacientes.paciente')),
            ],
        ),
    ]
