# Generated by Django 4.2.23 on 2025-07-21 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
        ('contato_emergencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionalSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('sexo_biologico', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('especialidade', models.CharField(max_length=100)),
                ('numero_registro', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contato_emergencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='contato_emergencia.contatoemergencia')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='endereco.endereco')),
            ],
        ),
    ]
